parameters:
    locale: 'en'
    app_locales: en|es

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $locales: '%app_locales%'
            string $defaultLocale: '%locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Listener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }
